######################################################################
# Automatically generated by qmake (3.0) Mo. Aug. 6 14:22:41 2018
######################################################################

TEMPLATE = app
TARGET = mqtt-dashboard
INCLUDEPATH += .
QT += core 
QT += widgets
LIBS += -lmosquittopp -lmosquitto

# Input
HEADERS += tile.h grid.h SquareFrame.h FixedGridLayout.h
SOURCES += mqtt-dashboard.cpp tile.cpp grid.cpp FixedGridLayout.cpp
